set(_CATKIN_CURRENT_PACKAGE "ur5_vs")
set(ur5_vs_VERSION "0.0.0")
set(ur5_vs_MAINTAINER "rekha <rekha@todo.todo>")
set(ur5_vs_PACKAGE_FORMAT "1")
set(ur5_vs_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "moveit_ros_move_group" "moveit_ros_planning_interface" "actionlib" "control_msgs" "tf" "geometry_msgs" "visualization_msgs" "message_generation" "pcl_ros" "pcl_conversions")
set(ur5_vs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "actionlib" "control_msgs" "tf" "geometry_msgs" "visualization_msgs" "message_runtime" "moveit_ros_move_group" "moveit_ros_planning_interface" "pcl_ros" "pcl_conversions")
set(ur5_vs_BUILDTOOL_DEPENDS "catkin")
set(ur5_vs_BUILDTOOL_EXPORT_DEPENDS )
set(ur5_vs_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "actionlib" "control_msgs" "tf" "geometry_msgs" "visualization_msgs" "message_runtime" "moveit_ros_move_group" "moveit_ros_planning_interface" "pcl_ros" "pcl_conversions")
set(ur5_vs_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "actionlib" "control_msgs" "tf" "geometry_msgs" "visualization_msgs" "message_runtime" "moveit_ros_move_group" "moveit_ros_planning_interface" "pcl_ros" "pcl_conversions")
set(ur5_vs_TEST_DEPENDS )
set(ur5_vs_DOC_DEPENDS )
set(ur5_vs_URL_WEBSITE "")
set(ur5_vs_URL_BUGTRACKER "")
set(ur5_vs_URL_REPOSITORY "")
set(ur5_vs_DEPRECATED "")